[package]
name = "zenith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.16.0", features = ["boxed"] }

[features]
type_in_type = []
